---
# tasks file for apache

- name: Install base packages
  package:
    name: ['wget','tar','unzip']
    state: present

- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present